//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kredi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Movements
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Error : ingresar fecha")]
        public System.DateTime motionDay { get; set; }
        [Required(ErrorMessage = "Error : ingresar descripcion")]
        public string description { get; set; }
        [Required(ErrorMessage = "Error : ingresar monto")]
        public float movementValue { get; set; }
        [Required]
        public bool isMoneyWithdrawal { get; set; }
        [Required]
        public float balance { get; set; }
        [Required]
        public int LinesOfCredit_id { get; set; }
    
        public virtual LinesOfCredit LinesOfCredit { get; set; }
    }
}
