//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kredi.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.LinesOfCredit = new HashSet<LinesOfCredit>();
        }
    
        public int id { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El nombre es requirido !")]
        public string names { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Los apellidos son requiridos !")]
        public string surnames { get; set; }

        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "El correo es requirido !")]
        public string email { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "La contraseña es requirido !")]
        public string password { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El nombre del local es requirido !")]
        public string nameOfThePlace { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinesOfCredit> LinesOfCredit { get; set; }
    }
}
